FROM bmoorman/alpine:armhf-3.13

RUN apk add --no-cache \
    python3 \
    py3-requests \
 && apk add --no-cache --virtual .build-deps \
    build-base \
    py3-pip \
    py3-wheel \
    python3-dev \
 && pip3 install Adafruit-DHT \
 && apk del --no-cache .build-deps

COPY bin/ /usr/local/bin/

CMD ["sensor.py"]
